configuration:  
  projectName: configclient
server:
  port: 8002
message:
  greeting: Welcome to autoRefresh Config Server (the second and without profiles)!
spring:
  profiles:
    active: development
