user:
  role: User
server:
  port: 8004
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enable: true
  instance:
    statusPageUrlPath: /my_info
    healthCheckUrlPath: /my_health

security:
  user:
    name: root
    password: root2
