configuration:  
  projectName: configclient
server:
  port: 8001
message:
  greeting: 22Hello from the configuration! Probando a configurar por cuarta vez
spring:
  profiles:
    active: development
