configuration:  
  projectName: configclient
server:
  port: 8001
message:
  greeting: yala 22Hello from the configuration! Probando a configurar por cuarta vez45678908
spring:
  profiles:
    active: development
