user:
  role: User

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /my_info
    healthCheckUrlPath: /my_health

security:
  user:
    name: root
    password: root2
